---

- name: simple-provisining
  hosts: localhost
  connetion: local
  gather_facts: false
  vars:
    aws_region: ap-northeast-2
	vpc_name: lsh-vpc
	vpc_cidr_block: 10.210.10.0/16
	subnet_cidr_block: 10.210.11.0/24
	instance_image: ami-0b827f3319f7447c6
	ec2_key_name: lsh_class3
	instance_type: t3.nano
	
  tasks:
  - name: create vpc
    ec2_vpc_net:
	  name: "{{ vpc_name }}"
	  cidr_block: "{{ vpc_cidr_block }}"
	  region: "{{ aws_region }}"
	  tags:
	    Name: "{{ vpc_name }}"
	  tenancy: default
	register: result_vpc
    
  - name: Create subnet
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{ result_vpc.vpc.id }}"
      cidr: "{{ subnet_cidr_block }}"
      region: "{{ aws_region }}"
      tags:
        Name: webserver Subnet
    register: result_sunet
    
  - name: Create igw
    ec2_vpc_igw:
      region: "{{ aws_region }}"
      vpc_id: "{{ result_vpc.vpc.id }}"
      state: present
    register: result_igw